a=int(input("Enter a Frist Value : "))
b=int(input("Enter a Second Value : "))
c=int(input("Enter a Third Value : "))
d=(a*b*c)
e=(a+b+c)
#print("Multipulication a 3 Value", d)
#print("added a 3 Value", e)
f=(d/e)
print("divided Multi and Addition Values", f)
